---
version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile_app
        env_file: .env
        command: >
            bash -c "curl -XPUT http://elasticsearch:9200/$INDEX_NAME -H 'Content-Type: application/json' -d @mapping.json
            && flask run --host=0.0.0.0"
        ports:
            - 5813:5000
        volumes:
            - .:/opt/wiating
            - images:/images
        depends_on:
            - elasticsearch
            - rabbitmq

    elasticsearch:
        build:
            dockerfile: Dockerfile_elasticsearch
            context: .
            args:
                - ELASTIC_VERSION=7.5.1
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        volumes:
            - esdata01:/usr/share/elasticsearch/data
        restart: always

    rabbitmq:
        image: rabbitmq:latest
        ports:
            - 5672:5672
        restart: always

volumes:
    esdata01:
    images:
