""" Constants file for wiating backend
"""
AUTH0_CLIENT_ID='AUTH0_CLIENT_ID'
AUTH0_DOMAIN='AUTH0_DOMAIN'
AUTH0_CLIENT_SECRET='AUTH0_CLIENT_SECRET'
AUTH0_CALLBACK_URL='AUTH0_CALLBACK_URL'
AUTH0_AUDIENCE='AUTH0_AUDIENCE'
SECRET_KEY = 'SECRET_KEY'
S3_BUCKET = 'S3_BUCKET'
ES_CONNECTION_STRING = 'ES_CONNECTION_STRING'
INDEX_NAME = 'INDEX_NAME'
IMAGE_RESIZER_QUEUE = 'IMAGE_RESIZER_QUEUE'
DASHBOARD_CONFIG_FILE_PATH = 'DASHBOARD_CONFIG_FILE_PATH'
